/**
 * Mock data for UI development.
 *
 * TODO(backend): Sonny will replace these with real Supabase queries.
 * The lib functions in items.ts, circle.ts, etc. consume these mocks
 * until the backend is wired up.
 */

import type {
  Item,
  BorrowTransaction,
  WishlistItem,
  ActivityEntry,
} from '@/types/items';

/** Simple profile shape used by the UI layer. */
export interface MockProfile {
  id: string;
  full_name: string;
  avatar_url: string | null;
  phone: string | null;
  circle_id: string | null;
  created_at: string;
}

/** Simple circle member shape used by the UI layer. */
export interface MockMember {
  id: string;
  full_name: string;
  avatar_url: string | null;
  item_count: number;
}

export const mockCurrentUser: MockProfile = {
  id: 'user-1',
  full_name: 'Sarah M.',
  avatar_url: null,
  phone: '+971501234567',
  circle_id: 'circle-1',
  created_at: '2025-01-15T10:00:00Z',
};

export const mockCircle = {
  id: 'circle-1',
  name: 'The Atelier Circle',
  created_at: '2025-01-15T10:00:00Z',
};

export const mockMembers: MockMember[] = [
  { id: 'user-1', full_name: 'Sarah M.', avatar_url: null, item_count: 12 },
  { id: 'user-2', full_name: 'Mona A.', avatar_url: null, item_count: 8 },
  { id: 'user-3', full_name: 'Khalid R.', avatar_url: null, item_count: 5 },
  { id: 'user-4', full_name: 'Lina F.', avatar_url: null, item_count: 7 },
];

export const mockItems: Item[] = [
  {
    id: 'item-1',
    owner_id: 'user-1',
    owner_name: 'Sarah M.',
    circle_id: 'circle-1',
    brand: 'Chanel',
    model_name: 'Classic Flap',
    category: 'bag',
    color: 'Black',
    size: 'Medium',
    material: 'Caviar Leather',
    condition: 'like_new',
    status: 'borrowed',
    purchase_price: 38000,
    estimated_value: 42000,
    currency: 'AED',
    notes: 'Gold hardware, 2022 edition',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: 'item-2',
    owner_id: 'user-1',
    owner_name: 'Sarah M.',
    circle_id: 'circle-1',
    brand: 'Hermès',
    model_name: 'Birkin 30',
    category: 'bag',
    color: 'Gold',
    size: '30cm',
    material: 'Togo Leather',
    condition: 'good',
    status: 'available',
    purchase_price: 85000,
    estimated_value: 95000,
    currency: 'AED',
    notes: 'Palladium hardware',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-01-20T10:00:00Z',
    updated_at: '2025-01-20T10:00:00Z',
  },
  {
    id: 'item-3',
    owner_id: 'user-1',
    owner_name: 'Sarah M.',
    circle_id: 'circle-1',
    brand: 'Rolex',
    model_name: 'Datejust 36',
    category: 'watch',
    color: 'Silver',
    size: '36mm',
    material: 'Stainless Steel',
    condition: 'like_new',
    status: 'available',
    purchase_price: 35000,
    estimated_value: 38000,
    currency: 'AED',
    notes: 'Fluted bezel, Jubilee bracelet',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-03-01T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
  },
  {
    id: 'item-4',
    owner_id: 'user-1',
    owner_name: 'Sarah M.',
    circle_id: 'circle-1',
    brand: 'Cartier',
    model_name: 'Love Bracelet',
    category: 'jewelry',
    color: 'Gold',
    size: '17cm',
    material: '18k Yellow Gold',
    condition: 'good',
    status: 'available',
    purchase_price: 28000,
    estimated_value: 30000,
    currency: 'AED',
    notes: '4 diamonds',
    primary_image_url: null,
    is_private: true,
    is_lendable: false,
    authenticity_verified: true,
    created_at: '2025-02-15T10:00:00Z',
    updated_at: '2025-02-15T10:00:00Z',
  },
  {
    id: 'item-5',
    owner_id: 'user-1',
    owner_name: 'Sarah M.',
    circle_id: 'circle-1',
    brand: 'Christian Louboutin',
    model_name: 'Pigalle Follies',
    category: 'shoes',
    color: 'Black',
    size: '38',
    material: 'Patent Leather',
    condition: 'good',
    status: 'available',
    purchase_price: 12000,
    estimated_value: 10000,
    currency: 'AED',
    notes: '100mm heel',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: false,
    created_at: '2025-04-01T10:00:00Z',
    updated_at: '2025-04-01T10:00:00Z',
  },
  {
    id: 'item-6',
    owner_id: 'user-2',
    owner_name: 'Mona A.',
    circle_id: 'circle-1',
    brand: 'Dior',
    model_name: 'Lady Dior',
    category: 'bag',
    color: 'Beige',
    size: 'Medium',
    material: 'Lambskin',
    condition: 'like_new',
    status: 'available',
    purchase_price: 32000,
    estimated_value: 34000,
    currency: 'AED',
    notes: 'Cannage stitching',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-01-25T10:00:00Z',
    updated_at: '2025-01-25T10:00:00Z',
  },
  {
    id: 'item-7',
    owner_id: 'user-2',
    owner_name: 'Mona A.',
    circle_id: 'circle-1',
    brand: 'Van Cleef & Arpels',
    model_name: 'Alhambra Bracelet',
    category: 'jewelry',
    color: 'Gold',
    size: 'One Size',
    material: '18k Gold, Mother of Pearl',
    condition: 'new',
    status: 'available',
    purchase_price: 22000,
    estimated_value: 24000,
    currency: 'AED',
    notes: '5 motifs',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-03-15T10:00:00Z',
    updated_at: '2025-03-15T10:00:00Z',
  },
  {
    id: 'item-8',
    owner_id: 'user-3',
    owner_name: 'Khalid R.',
    circle_id: 'circle-1',
    brand: 'Omega',
    model_name: 'Speedmaster Moonwatch',
    category: 'watch',
    color: 'Black',
    size: '42mm',
    material: 'Stainless Steel',
    condition: 'like_new',
    status: 'available',
    purchase_price: 25000,
    estimated_value: 27000,
    currency: 'AED',
    notes: 'Hesalite crystal',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: true,
    created_at: '2025-02-10T10:00:00Z',
    updated_at: '2025-02-10T10:00:00Z',
  },
  {
    id: 'item-9',
    owner_id: 'user-4',
    owner_name: 'Lina F.',
    circle_id: 'circle-1',
    brand: 'Gucci',
    model_name: 'Marmont Shoulder Bag',
    category: 'bag',
    color: 'Red',
    size: 'Small',
    material: 'Matelasse Leather',
    condition: 'good',
    status: 'available',
    purchase_price: 15000,
    estimated_value: 14000,
    currency: 'AED',
    notes: 'GG hardware',
    primary_image_url: null,
    is_private: false,
    is_lendable: true,
    authenticity_verified: false,
    created_at: '2025-04-10T10:00:00Z',
    updated_at: '2025-04-10T10:00:00Z',
  },
  {
    id: 'item-10',
    owner_id: 'user-4',
    owner_name: 'Lina F.',
    circle_id: 'circle-1',
    brand: 'Valentino',
    model_name: 'Rockstud Pumps',
    category: 'shoes',
    color: 'Nude',
    size: '37',
    material: 'Leather',
    condition: 'good',
    status: 'available',
    purchase_price: 8000,
    estimated_value: 7000,
    currency: 'AED',
    notes: '100mm',
    primary_image_url: null,
    is_private: true,
    is_lendable: false,
    authenticity_verified: false,
    created_at: '2025-05-01T10:00:00Z',
    updated_at: '2025-05-01T10:00:00Z',
  },
];

export const mockBorrowTransactions: BorrowTransaction[] = [
  {
    id: 'borrow-1',
    item_id: 'item-1',
    item_brand: 'Chanel',
    item_model: 'Classic Flap',
    borrower_id: 'user-2',
    borrower_name: 'Mona A.',
    lender_id: 'user-1',
    lender_name: 'Sarah M.',
    status: 'active',
    borrower_note: 'For a wedding this weekend',
    lender_note: null,
    requested_at: '2025-07-20T10:00:00Z',
    approved_at: '2025-07-21T10:00:00Z',
    borrowed_at: '2025-07-22T10:00:00Z',
    returned_at: null,
    completed_at: null,
  },
];

export const mockWishlistItems: WishlistItem[] = [
  {
    id: 'wl-1',
    user_id: 'user-1',
    owner_name: 'Sarah M.',
    brand: 'Bottega Veneta',
    model_name: 'The Pouch',
    category: 'bag',
    target_price: 18000,
    current_savings: 12000,
    currency: 'AED',
    notes: 'Intrecciato leather, medium size',
    image_url: null,
    is_private: false,
    fulfilled: false,
    priority: 1,
    created_at: '2025-06-01T10:00:00Z',
  },
  {
    id: 'wl-2',
    user_id: 'user-1',
    owner_name: 'Sarah M.',
    brand: 'Patek Philippe',
    model_name: 'Nautilus 5711',
    category: 'watch',
    target_price: 250000,
    current_savings: 75000,
    currency: 'AED',
    notes: 'Blue dial dream',
    image_url: null,
    is_private: true,
    fulfilled: false,
    priority: 2,
    created_at: '2025-05-15T10:00:00Z',
  },
  {
    id: 'wl-3',
    user_id: 'user-1',
    owner_name: 'Sarah M.',
    brand: 'Loewe',
    model_name: 'Puzzle Bag',
    category: 'bag',
    target_price: 14000,
    current_savings: 14000,
    currency: 'AED',
    notes: 'Small, tan color',
    image_url: null,
    is_private: false,
    fulfilled: true,
    priority: 3,
    created_at: '2025-03-20T10:00:00Z',
  },
  {
    id: 'wl-4',
    user_id: 'user-2',
    owner_name: 'Mona A.',
    brand: 'Saint Laurent',
    model_name: 'Sac de Jour',
    category: 'bag',
    target_price: 16000,
    current_savings: 8000,
    currency: 'AED',
    notes: 'Looking for a versatile day bag',
    image_url: null,
    is_private: false,
    fulfilled: false,
    priority: 1,
    created_at: '2025-06-10T10:00:00Z',
  },
  {
    id: 'wl-5',
    user_id: 'user-4',
    owner_name: 'Lina F.',
    brand: 'Audemars Piguet',
    model_name: 'Royal Oak 15500',
    category: 'watch',
    target_price: 180000,
    current_savings: 45000,
    currency: 'AED',
    notes: 'Grail watch — blue dial',
    image_url: null,
    is_private: false,
    fulfilled: false,
    priority: 1,
    created_at: '2025-04-05T10:00:00Z',
  },
];

export const mockActivity: ActivityEntry[] = [
  {
    id: 'act-1',
    type: 'borrow_requested',
    user_id: 'user-2',
    actor_name: 'Mona A.',
    summary: 'requested to borrow your Chanel Classic Flap',
    item_id: 'item-1',
    item_brand: 'Chanel',
    borrow_id: 'borrow-1',
    metadata: null,
    created_at: '2025-07-20T10:00:00Z',
  },
  {
    id: 'act-2',
    type: 'borrow_active',
    user_id: 'user-2',
    actor_name: 'Mona A.',
    summary: 'is now borrowing your Chanel Classic Flap',
    item_id: 'item-1',
    item_brand: 'Chanel',
    borrow_id: 'borrow-1',
    metadata: null,
    created_at: '2025-07-22T10:00:00Z',
  },
  {
    id: 'act-3',
    type: 'item_added',
    user_id: 'user-4',
    actor_name: 'Lina F.',
    summary: 'added a new item: Valentino Rockstud Pumps',
    item_id: 'item-10',
    item_brand: 'Valentino',
    borrow_id: null,
    metadata: null,
    created_at: '2025-05-01T10:00:00Z',
  },
  {
    id: 'act-4',
    type: 'wishlist_item_added',
    user_id: 'user-4',
    actor_name: 'Lina F.',
    summary: 'is dreaming of an Audemars Piguet Royal Oak',
    item_id: null,
    item_brand: 'Audemars Piguet',
    borrow_id: null,
    metadata: null,
    created_at: '2025-04-05T10:00:00Z',
  },
  {
    id: 'act-5',
    type: 'item_added',
    user_id: 'user-3',
    actor_name: 'Khalid R.',
    summary: 'added an Omega Speedmaster Moonwatch',
    item_id: 'item-8',
    item_brand: 'Omega',
    borrow_id: null,
    metadata: null,
    created_at: '2025-02-10T10:00:00Z',
  },
];
